version: '2'
services:
  console:
    build:
      context: ./services/console
      dockerfile: Dockerfile
    volumes_from:
      - php
    tty: true
  web:
    image: nginx:1.11.1
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./services/nginx/config:/etc/nginx/conf.d
  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    # volumes:
    #   - ./app/drupal/sites/default/settings.php:/mnt/app/drupal/sites/default/settings.php
    volumes_from:
      - container:drupal-unison-sync:rw
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "123123"
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis:3.2.1
    ports:
      - "6379:6379"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "root"
volumes:
  drupal-unison-sync:
    external: true
  db:
    driver: local
